#
# Naturally you need to adapt this to make work for your project
#

service:
	pip install pip -U
	pip install eve
	pip install pandas
	pip install pandas
	pip install benford_py
	#sudo apt-get install -y build-essential libbz2-dev libssl-dev libreadline-dev \ libsqlite3-dev tk-dev 
	#sudo apt-get install -y libpng-dev libfreetype6-dev 
	pip install matplotlib
	pyenv install anaconda3-4.3.1
	alias ANA="pyenv activate anaconda3-4.3.1"
start:
	python BenfordLawVerificationService.py
